theme: minima
title: Untitled
author: GitHub User
description: > # this means to ignore newlines until "baseurl:"
  I have written an awesome description for my new site here. I can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in my feed.xml site description.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
